---
  - hosts: all
    sudo: true
    vars:
      document_root: /var/www/public
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    tasks:
      - name: install Helper packages
        apt: name={{ item }} state=present
        with_items:
          - vim
          - nano
          - tree
          - mlocate
    roles:
      - webserver
      - database
      - composer
      - daemonize
      - mailhog
      - project-init
      - motd
