---

- name: Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - curl
    - git

- name: Installing composer
  shell: >
    curl -sS https://getcomposer.org/installer | php -- --install-dir={{ composer_path }} --filename=composer
  args:
    creates: "{{ composer_path }}/composer"

- name: Get stat of composer file
  stat:
    path: "{{ composer_path }}/composer"
  register: composer_stat

- name: Get date for composer update
  shell: >
    date --date='{{ composer_update_day }} days ago' +'%s'
  register: composer_last_update
  changed_when: False

- name: Update composer if necessary
  shell: >
    {{ composer_path }}/composer selfupdate
  when: composer_last_update.stdout|int > composer_stat.stat.mtime|int
