---
- name: Install apache
  apt: name=apache2 state=present

- name: Copy new virtual host config file
  template:
    src=virtual-hosts.conf.j2
    dest=/etc/apache2/sites-available/default.local.conf
  notify:
   - reload apache

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Enable new default virtual host
  file:
    src=/etc/apache2/sites-available/default.local.conf
    dest=/etc/apache2/sites-enabled/default.local.conf
    state=link
  notify:
    - reload apache

- name: clean /var/www directory
  file:
    state: absent
    path: /var/www/

- name: Set group, owner and permissions for /var/www
  file:
    path: /var/www/public
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0775
    recurse: yes

- name: Ad vagrant user to www-data group
  user:
    name: vagrant
    groups: vagrant,www-data,sudo,netdev
