---
- name: install php7.0
  apt: name={{ item }} state=latest
  with_items:
    - php7.0
    - php7.0-mysql
    - libapache2-mod-php7.0
    - php7.0-cli
    - php7.0-cgi
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
    - php7.0-json
    - php7.0-intl
    - php7.0-curl
